import Head from 'next/head';
import React, { Suspense } from 'react';
import dynamic from 'next/dynamic';
import { BeatLoader } from 'react-spinners';

const DynamicThreeScene = dynamic(() => import('./ThreeScene'), {
  ssr: false,
});

export const Homepage = () => (
  <>
    <Head>
      <title>bryantcodes.art</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="w-screen h-screen bg-black">
      <h1 className="fixed top-0 left-0 z-10 p-4 font-mono font-bold text-white bg-blue">bryantcodes.art</h1>

      <a
        href="mailto:hello@bryantcodes.art?subject=Hello!&body=(if you're not unsure how to start this email, just tell me your favorite kind of pizza)"
        className="fixed bottom-0 right-0 z-10 p-4 font-mono font-bold text-white underline bg-blue"
        target="_blank"
        rel="noreferrer"
      >
        contact
      </a>

      <Suspense
        fallback={(
          <div className="absolute -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2">
            <BeatLoader color="#ffffff" />
          </div>
        )}
      >
        <DynamicThreeScene />
      </Suspense>
    </main>
  </>
);
