import Head from 'next/head';
import React, { Suspense } from 'react';
import dynamic from 'next/dynamic';
import { BeatLoader } from 'react-spinners';
import { CustomCursorHover } from './CustomCursor';
import { SiteData } from './SiteData';

const DynamicThreeCanvas = dynamic(() => import('./ThreeCanvas'), {
  ssr: false,
});

export const contactHref = `mailto:hello@bryantcodes.art?subject=${encodeURIComponent('Hello, Bryant!')}&body=${encodeURIComponent("(If you're unsure how to start this email, just tell me your favorite kind of pizza to break the ice.)")}`;

export const ThreePage = ({ siteData }:{siteData:SiteData}) => (
  <>
    <Head>
      <title>bryantcodes.art</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="w-screen h-screen bg-white">
      <div
        className="fixed top-0 left-0 text-[1rem] px-[1rem] py-[1rem] font-mono text-white bg-[red] tracking-wide z-[88888888] sm:px-[2rem]"
        style={{
          filter: 'drop-shadow(0 0 0.2rem black) drop-shadow(0 0 0.2rem black)',
        }}
      >
        CONTACT:
        {' '}
        <CustomCursorHover cursor="contact">
          <a
            href={contactHref}
            className="underline"
            target="_blank"
            rel="noreferrer"
          >
            {' '}
            hello@bryantcodes.art
          </a>
        </CustomCursorHover>
      </div>

      <div
        className="fixed bottom-0 right-0 text-[1rem] px-[1rem] py-[1rem] font-mono text-white bg-blue tracking-wide z-[88888888] sm:px-[2rem]"
        style={{
          filter: 'drop-shadow(0 0 0.2rem black) drop-shadow(0 0 0.2rem black)',
        }}
      >
        AVAILABLE: OCTOBER+
      </div>
      <Suspense
        fallback={(
          <div className="absolute -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2">
            <BeatLoader color="#ffffff" />
          </div>
          )}
      >
        <DynamicThreeCanvas siteData={siteData} />
      </Suspense>
    </main>
  </>
);
