import React, { Suspense } from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { BeatLoader } from 'react-spinners';
import { SiteData } from './SiteData';
import { CTA } from './CTA';
import { useMobileViewPortUnits } from './useMobileViewPortUnits';

const DynamicThreeCanvas = dynamic(() => import('./ThreeCanvas'), {
  ssr: false,
});

export const ThreePage = ({ siteData }:{siteData:SiteData}) => {
  useMobileViewPortUnits();
  return (
    <>
      <Head>
        <title>bryantcodes.art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main className="w-screen h-[calc(100*var(--vh))] font-sans bg-white ">
        <CTA />
        {/* <div
          className={`
            fixed bottom-0 right-0 text-[1rem] px-[1rem] py-[1rem] font-mono
            text-black bg-yellow tracking-wide z-[88888888] sm:px-[2rem]
            ${showCTAs ? '' : 'translate-y-full'} transition-transform
          `}
          style={{
            filter: 'drop-shadow(0 0 0.2rem black) drop-shadow(0 0 0.2rem black)',
          }}
        >
          AVAILABLE: Q4
        </div> */}
        <Suspense
          fallback={(
            <div className="absolute -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2">
              <BeatLoader color="#ffffff" />
            </div>
          )}
        >
          <DynamicThreeCanvas siteData={siteData} />
        </Suspense>
      </main>
    </>
  );
};
